spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:30000/jjick-da?characterEncoding=UTF-8&useTimezone=true&serverTimezone=Asia/Seoul
    username: jjick-da
    password: Welcome1!
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  web:
    resources:
      static-locations: file:src/main/resources/static/
  servlet:
    multipart:
      # 단일 파일 최대 용량, default: 1MB
      max-file-size: 10MB
      # 여러 파일 최대 용량, default: 10MB
      max-request-size: 100MB
  devtools:
    livereload:
      enabled: true
  freemarker:
    cache: false
  thymeleaf:
    prefix: classpath:/templates/
    check-template-location: true
    suffix: .html
    mode: HTML5
    cache: false
    template-resolver-order: 0

mybatis:
  mapper-locations: mapper/*.xml

logging:
  config: classpath:logback/logback-local.xml


file:
  directory: /Users/igor/Desktop/upload/